### ISSUE TITLE
Segredos no código e configuração por ambiente

### ISSUE THREAD

**Issue by mstrcnvs** [jeangen/projeto-vaga-backend#1]
Boa tarde Jean, tudo bem?

Percebi que os segredos de conexão ao banco de dados estão armazenados no código, isso fere algumas políticas de segurança, assim como boas práticas de configuração por ambiente.

> A litmus test for whether an app has all config correctly factored out of the code is whether the codebase could be made open source at any moment, without compromising any credentials.
https://12factor.net/config

Qual seria sua sugestão para corrigir esses pontos?

https://github.com/jeangen/projeto-vaga-backend/blob/6dae3e91c18c46fe49dba4166b24d9216f7708e2/ACMEVita/manage.py#L7

**Comment by jeangen** [comment]
Colocaria os segredos em um arquivo com variáveis de ambiente quando fosse usar e manteria eles guardados em algum serviço como o parameter store da AWS.

**Comment by mstrcnvs** [comment]
Obrigado Jean!
