### ISSUE TITLE
Repetição de código 

### ISSUE THREAD

**Issue by mstrcnvs** [jeangen/projeto-vaga-backend#3]
Boa tarde Jean, tudo bem?

Percebi que o código abaixo está repetido em mais de 3 arquivos, e trata-se de uma configuração da aplicação.

https://github.com/jeangen/projeto-vaga-backend/blob/6dae3e91c18c46fe49dba4166b24d9216f7708e2/ACMEVita/ACMEVita/src/employees/views.py#L8-L10

Qual seria sua sugestão para evitarmos repetição de código nesse ponto?

Abs.

**Comment by jeangen** [comment]
Usaria um arquivo da espécie config.py (estou me inspirando em alguns frameworks que ja usei e apresentam esse tipo de estrutura ex: scrapy, djangorest) onde deixaria essas configurações para os desenvolvedores setarem de acordo com o uso.

**Comment by mstrcnvs** [comment]
Obrigado Jean!
