### ISSUE TITLE
Validação de dados

### ISSUE THREAD

**Issue by mstrcnvs** [jeangen/projeto-vaga-backend#4]
Boa tarde Jean, tudo bem?

Percebi que na view de criação de colaborador, não há validação dos dados de entrada, ou seja, é possível especificar uma string qualquer para o campo `have_dependents` que, por sua vez, possui o tipo `Integer`, gerando assim um erro 500.

Quais seriam suas sugestões para que API validasse os dados de entrada, instruindo assim, os usuários da API, sobre o que devem enviar no payload?
 
https://github.com/jeangen/projeto-vaga-backend/blob/6dae3e91c18c46fe49dba4166b24d9216f7708e2/ACMEVita/ACMEVita/src/employees/views.py#L39-L49

**Comment by jeangen** [comment]
Um método de validação que verifica o tipo de dado e outras possíveis características que aquele dado possui, assim podemos usar um try, excepet dentro deste método para tentar enviar o dado ou retornar um erro.

**Comment by mstrcnvs** [comment]
Obrigado Jean!
